services:
  {{ cookiecutter.package_slug_kebab }}:
    build: .
    restart: unless-stopped
    environment:
      - {{ cookiecutter.package_slug|upper }}_DEBUG=${{ "{" }}{{ cookiecutter.package_slug|upper }}_DEBUG:?Please export {{ cookiecutter.package_slug|upper }}_DEBUG as an environment variable{{ "}" }}
