name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key:
            {{ "${{ runner.os }}-${{ hashFiles('**/pyproject.toml', '**/setup.cfg') }}" }}
          restore-keys: |
            {{ "${{ runner.os }}-}" }}

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade poetry
          poetry install

      - name: Test
{%- if cookiecutter.is_open_source != "y" %}
        run: ./scripts/test.sh
{%- else %}
        shell: bash
        run: |
          ./scripts/test.sh
          poetry run coverage xml

      - name: Report Coverage
        uses: codecov/codecov-action@v1.0.6
{% endif %}