name: "Python application: {{ cookiecutter.project_name }}"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "{{ cookiecutter.python_version }}"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pip-tools
          pip-sync requirements/dev.txt
          pip install .[dev]

      - name: Lint
        run: |
          ruff check --fix src/
          pylint src/
          ruff format --check src/ tests/
          pyright src/

      - name: Test
        run: |
          pytest -s --cov=src/ --cov-report=term-missing --cov-report html tests/
